const publishPreview = {
    swiperList:[
        {
          id:1,
          path:`http://112.74.54.65:3000/storage/20220227/0-17f38fffeb4.png`
        }
     ],
     requirementList:[
       {
         id:1,
         path:"../../images/zazhi3.png",
         remark:"禁止掺杂"
       },
       {
         id:2,
         path:"../../images/30kg2.png",
         remark:"30斤以内"
       },{
         id:3,
         path:"../../images/water3-1.png",
         remark:"保持干燥"
       }
     ],
     categorySquareList:[
       {
         id:1,
         path:"../../images/classify_icon011.png",
         title:"纸皮",
         detail:"纸皮，废纸"
       },{
         id:2,
         path:"../../images/classify_icon021-1.png",
         title:"塑料",
         detail:"塑料瓶"
       },{
         id:3,
         path:"../../images/classify_icon031-1.png",
         title:"金属",
         detail:"不锈钢"
       },{
         id:4,
         path:"../../images/classify_icon041.png",
         title:"其它",
         detail:"衣服，废品"
       }
     ],
     hotList:[
       {
         id:1,
         title:"二手物品折旧回收",
         detail:"昨日参与人数140",
         src:"http://112.74.54.65:3000/storage/20220303/0-17f4f932a08.png"

       },
       {
         id:2,
         title:"代拆代扔服务",
         detail:"今日参与人数150",
         src:"http://112.74.54.65:3000/storage/20220303/0-17f4f96d0cc.png"
       }
     ],
     imageSrc:"../../images/xunhuan.svg"
}
export default publishPreview